services:
  namenode:
    image: bde2020/hadoop-namenode:latest
    container_name: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=test-cluster
    volumes:
      - namenode:/hadoop/dfs/name
    networks:
      - hadoop-net

  datanode:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - datanode:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop-net

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:latest
    container_name: resourcemanager
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    depends_on:
      - namenode
    networks:
      - hadoop-net

  nodemanager:
    image: bde2020/hadoop-nodemanager:latest
    container_name: nodemanager
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    depends_on:
      - resourcemanager
    networks:
      - hadoop-net

  historyserver:
    image: bde2020/hadoop-historyserver:latest
    container_name: historyserver
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - historyserver:/hadoop/yarn/timeline
    depends_on:
      - namenode
    networks:
      - hadoop-net

  spark:
    image: bde2020/spark-master:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MASTER_HOST=spark-master
    networks:
      - hadoop-net

  spark-worker:
    image: bde2020/spark-worker:latest
    container_name: spark-worker
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark
    networks:
      - hadoop-net

volumes:
  namenode:
  datanode:
  historyserver:

networks:
  hadoop-net:
